/**
 * Verification-token rules (Slice 4A foundation).
 *
 * The token is the ENTIRE QR payload and the only thing a public verification
 * lookup accepts. It is generated by the database from
 * `gen_random_bytes(32)` — never here, and never in a browser — because a
 * token is a bearer credential and the only safe generator is a CSPRNG under
 * the server's control.
 *
 * What lives here is validation and the shape rule, so a malformed lookup is
 * rejected before it reaches a query, and so the properties the token must
 * have are written down somewhere testable.
 */

/** 32 bytes rendered as hex. Fixed width, so length alone is a strong filter. */
const TOKEN_PATTERN = /^[a-f0-9]{64}$/

export const VERIFICATION_TOKEN_LENGTH = 64

/** Mirrors the CHECK constraint on `certificates.verification_token`. */
export function isValidVerificationToken(candidate: string): boolean {
  return TOKEN_PATTERN.test(candidate)
}

/**
 * Normalises a token a person typed or a scanner produced.
 *
 * QR scanners and hand-transcription both introduce case and whitespace
 * variation; the stored form is lower-case hex. Normalising here means the
 * public lookup compares one canonical shape rather than trying variants,
 * which is what keeps the query a single indexed equality.
 */
export function normalizeVerificationToken(raw: string): string {
  return raw.trim().toLowerCase()
}

/**
 * Entropy, stated so the property is testable rather than assumed.
 *
 * 32 bytes is 256 bits. At any plausible request rate, guessing one is not a
 * threat model — which is why the public endpoint can answer a bare token
 * without the lookup itself becoming an enumeration oracle. Sequential or
 * derived tokens would make that false, so 4A refuses them at the CHECK
 * constraint and the database generates them from a CSPRNG.
 */
export const VERIFICATION_TOKEN_ENTROPY_BITS = 256

/**
 * Whether a set of tokens shows any sign of being sequential or derived.
 *
 * Used by pgTAP and the unit suite as a sanity check on generated tokens.
 * It cannot prove randomness — nothing cheap can — but it does catch the
 * failure that would actually happen: someone replacing the generator with a
 * counter, a hash of the id, or the serial.
 */
export function looksNonSequential(tokens: readonly string[]): boolean {
  if (tokens.length < 2) return true

  const unique = new Set(tokens)
  if (unique.size !== tokens.length) return false

  // A counter or a shared derivation shows up as a long common prefix.
  const [first, ...rest] = tokens as [string, ...string[]]
  for (const other of rest) {
    let shared = 0
    while (shared < first.length && first[shared] === other[shared]) shared += 1
    // 8 hex characters of accidental agreement between two 64-character
    // random strings is already vanishingly unlikely.
    if (shared >= 8) return false
  }
  return true
}
